### Listar pedidos
GET http://localhost:3002/pedidos

### Criar pedido
POST http://localhost:3002/pedidos
Content-Type: application/json

{
  "cliente_id": 1,
  "itens": [
    {
      "produto_id": 1,
      "quantidade": 2,
      "preco_unitario": 150.00
    }
  ]
}

### Buscar pedido por ID
GET http://localhost:3002/pedidos/1